version: '3'
services:
  node:
    image: "nest-guide-nodeimg-${NODE_ENV}"
    container_name: "nest-guide-node-${NODE_ENV}"
    restart: on-failure
    env_file:
      - "../env/.env.mongodb-${NODE_ENV}"
    build:
      context: ..
      dockerfile: "devops/Dockerfile-${NODE_ENV}"
    ports:
      - '3000:3000'
      - "30000:9229"
    volumes:
      - ../src:/projectFiles/src
      - ../test:/projectFiles/test
      - ../env:/projectFiles/env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "nest-guide-mongodb-${NODE_ENV}"
    restart: on-failure
    env_file:
      - "../env/.env.mongodb-${NODE_ENV}"
    ports:
      - '27017:27017'
    volumes:
      - "../db/${NODE_ENV}/data:/data/db"
