FROM node:18.16.0 as nest-guide-nodeimg-prod

WORKDIR /projectFiles
COPY ../package.json ../tsconfig.json ../tsconfig.build.json ../nest-cli.json ./
RUN npm install
ADD ../src src
RUN npm run build
RUN npm prune --production
CMD ["node", "./dist/main.js"]
