FROM node:18.16.0 as nest-guide-nodeimg-test

WORKDIR /projectFiles

COPY ../package.json ../tsconfig.json ./

RUN npm install

# the command prevents the application from starting after the container is created,
# but keeps the container available
CMD ["tail", "-f", "/dev/null"]
