version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ValoryDB
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
