version: '3'
services:
  node:
    image: nodeapp
    container_name: node
    restart: on-failure
    env_file:
      - env/.env.mongodb-dev
      - env/.env.ravoly-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/projectFiles/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: on-failure
    env_file:
      - env/.env.mongodb-dev
    ports:
      - '27017:27017'
    volumes:
      - ./db/data:/data/db
