FROM node:18.16.0 as nest-guide-nodeimg-prod

WORKDIR /projectFiles

COPY ../package.json ../tsconfig.json ../tsconfig.build.json ../nest-cli.json ./

RUN npm install
RUN npm run build

ENTRYPOINT ["npm", "run", "start:prod"]
