# Base image for Node
FROM node:18.16.0 as nodeimg-debug

WORKDIR /projectFiles

COPY ../package.json package.json
COPY ../tsconfig.json tsconfig.json
COPY ../tsconfig.build.json tsconfig.build.json
COPY ../nodemon.json nodemon.json

RUN npm install

ENTRYPOINT [ "npm" ]

CMD [ "run", "start:nodemon" ]
