FROM node:18.16.0 as nodeimg-prod

WORKDIR /projectFiles

COPY ../package.json package.json
COPY ../tsconfig.json tsconfig.json
COPY ../tsconfig.build.json tsconfig.build.json
COPY ../nest-cli.json nest-cli.json

RUN npm install
RUN npm run build

ENTRYPOINT ["npm", "run", "start:prod"]
