# Base image for Node
FROM node:18.16.0 as nodeimg-test

# Copy project files
WORKDIR /projectFiles
COPY ../package.json ./tsconfig.json ./

# Install dependencies and build the project
RUN npm install

# Expose necessary ports
EXPOSE 3000

# the command prevents the application from starting after the container is created,
# but keeps the container available
CMD ["tail", "-f", "/dev/null"]
