name: commit-workflow
run-name: commit-workflow-runner

on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restoring cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/npm.lock') }}

      - name: Installing packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Get file changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Echo file changes
        id: hello
        run: |
          echo Added files: ${{ steps.file_changes .outputs.files_added }}
          echo Changed files: ${{ steps.file_changes .outputs.files_modified }}
          echo Removed files: ${{ steps.file_changes .outputs.files_removed }}
        if: ${{ always() && (steps.file_changes .outputs.files_added || steps.file_changes .outputs.files_modified) }}

      - name: Prettier Checking
        if: ${{ always() && (steps.file_changes .outputs.files_added || steps.file_changes .outputs.files_modified) }}
#        run: npm run prettier --config .prettierrc.json --ignore-path .prettierignore  ${{ steps.file_changes .outputs.files_added }} ${{ steps.file_changes .outputs.files_modified }} --fix
        run: npm run prettier --config .prettierrc.json --ignore-path .prettierignore ${{ steps.changed-files.outputs.all_changed_files }} --fix

#      - name: ESLint Checking
#        if: ${{ always() && (steps.file_changes .outputs.files_added || steps.file_changes .outputs.files_modified) }}
#        run: npm run eslint --config ./.eslintrc.js --ignore-path ./.eslintignore ${{ steps.file_changes .outputs.files_added }} ${{ steps.file_changes .outputs.files_modified }} --fix
