name: Publish Docker

on:
  pull_request_target:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/GRD-1/Nest-guide/node-img
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.NEST_GUIDE_WORKFLOW_TOKEN }}
          dockerfile: devops/Dockerfile-prod
