name: Release
run-name: release-workflow-runner

on:
#  workflow_dispatch:
#  push:
  pull_request_target:
    branches:
      - main

jobs:
  regression-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f devops/docker-compose.yml --env-file env/.env.test up -d

      - name: run tests
        run: |
          docker exec nest-guide-node-test npm run test:cov

      - name: stop docker containers and quit
        run: |
          docker stop $(docker ps -aq)

  prepare release:
    name: prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
            conventional-changelog-eslint@3.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.NEST-GUIDE_WORKFLOW_TOKEN }}

  build package:
    name: build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/GRD-1/Nest-guide/node-img
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.NEST_GUIDE_WORKFLOW_TOKEN }}
          dockerfile: devops/Dockerfile-prod
