name: tests workflow
on:
  push:
#  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f devops/docker-compose.yml --env-file env/.env.test up -d

      - name: run tests
        run: |
          docker exec nest-guide-node-test npm run test:cov

      - name: stop docker containers and quit
        run: |
          docker stop $(docker ps -aq)
